### ISSUE TITLE
TypeError since AppDaemon 4.4.2

### ISSUE THREAD

**Issue by chbndrhnns** [benleb/ad-automoli#118]
😩 **Describe the issue/bug**

There seems to be a timezone-related issue since AppDaemon 4.4.2:

```
2023-04-23 11:17:48.584456 WARNING office_kommode: ------------------------------------------------------------
2023-04-23 11:17:48.586182 WARNING office_kommode: Unexpected error in worker for App office_kommode:
2023-04-23 11:17:48.589760 WARNING office_kommode: Worker Ags: {}
2023-04-23 11:17:48.591700 WARNING office_kommode: ------------------------------------------------------------
2023-04-23 11:17:48.594162 WARNING office_kommode: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 160, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 402, in initialize
    daytimes = await self.build_daytimes(
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 1140, in build_daytimes
    await self.run_daily(
  File "/usr/lib/python3.10/site-packages/appdaemon/adapi.py", line 2661, in run_daily
    if event < now:
TypeError: can't compare offset-naive and offset-aware datetimes
2023-04-23 11:17:48.597784 WARNING office_kommode: ------------------------------------------------------------
```

😒 **Expected behavior**
No error

🎛️ **Configuration**
```yaml
```

🧠 **System**
 - AppDaemon: 4.4.2
   -  running mode: hassio-pluging
 - Home-Assistant: 2023.4
   -  running mode: hassio
 - Python: 
 - 
🗒️ **Logs** 

```log
log log log...
```

🧁 **Additional context**

**Comment by evildad** [comment]
Already fixed in the latest release
#115 
https://github.com/benleb/ad-automoli/releases/tag/v0.11.4

**Comment by chbndrhnns** [comment]
Great, thanks!
