### ISSUE TITLE
Xiaomi presence detectors cannot be used for illuminance calculation

### ISSUE THREAD

**Issue by chbndrhnns** [benleb/ad-automoli#19]
The xiaomi presence sensor exposes illumaniance, as well. But in its current implementation, automoli cannot understand it:

```python
2020-02-03 13:45:15.909403 WARNING stairs: Worker Ags: {'id': '23d7f4c23b8a462ba79fb75c728f0060', 'name': 'stairs', 'objectid': 'cb34a19c208c4a54bff6f9cd6028ef99', 'type': 'state', 'function': <bound method AutoMoLi.motion_detected_state of <automoli.AutoMoLi object at 0x7fc34196a520>>, 'attribute': 'state', 'entity': 'binary_sensor.motion_bathroom', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 2, 'kwargs': {'new': 'on', '__thread_id': 'thread-2'}}
2020-02-03 13:45:15.910372 WARNING stairs: ------------------------------------------------------------
2020-02-03 13:45:15.911616 WARNING stairs: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/automoli/automoli.py", line 302, in motion_detected_state
    self.motion_event("state_changed_detection", data, kwargs)
  File "/config/appdaemon/apps/automoli/automoli.py", line 325, in motion_event
    self.lights_on()
  File "/config/appdaemon/apps/automoli/automoli.py", line 344, in lights_on
    blocker = [
  File "/config/appdaemon/apps/automoli/automoli.py", line 347, in <listcomp>
    if float(self.get_state(sensor)) >= self.illuminance_threshold
ValueError: could not convert string to float: 'on'
```

Would it be possible to have a configurable entity attribute where the iilluminance value is taken from?

**Comment by jompa68** [comment]
i have same problem with an Fibaro motion sensor with illuminance.

`2020-02-06 20:18:26.635609 WARNING vrum: Unexpected error in worker for App vrum:
2020-02-06 20:18:26.636144 WARNING vrum: Worker Ags: {'id': 'd5966feff4964843be0c1f48963f5163', 'name': 'vrum', 'objectid': '61b7c5b4b1d54a939a89d65b016bcbd7', 'type': 'state', 'function': <bound method AutoMoLi.motion_detected_state of <automoli.AutoMoLi object at 0x7f99082c7be0>>, 'attribute': 'state', 'entity': 'binary_sensor.vardagsrum_sensortv_800', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'new': 'on', '__thread_id': 'thread-1'}}
2020-02-06 20:18:26.636630 WARNING vrum: ------------------------------------------------------------
2020-02-06 20:18:26.637446 WARNING vrum: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/automoli/automoli.py", line 302, in motion_detected_state
    self.motion_event("state_changed_detection", data, kwargs)
  File "/config/appdaemon/apps/automoli/automoli.py", line 325, in motion_event
    self.lights_on()
  File "/config/appdaemon/apps/automoli/automoli.py", line 344, in lights_on
    blocker = [
  File "/config/appdaemon/apps/automoli/automoli.py", line 347, in <listcomp>
    if float(self.get_state(sensor)) >= self.illuminance_threshold
TypeError: float() argument must be a string or a number, not 'dict'

2020-02-06 20:18:26.637897 WARNING vrum:`

**Comment by benleb** [comment]
Hm I use the same sensors, the problem seems to be somewhere else. Can you show the config which led to this error?
It seems the state of the configured sensor is `on` and not a number. Did you accidently configure the presence sensor instead of the illuminance one?
![image](https://user-images.githubusercontent.com/512997/74104361-4a0e2b00-4b54-11ea-8229-c1af3b948873.png)

**Comment by chbndrhnns** [comment]
There might be different sensors out there. Mine is connected via deconz. I do not see there is a separate illumination sensor.

![Screenshot_20200209-211340__01](https://user-images.githubusercontent.com/7534547/74109130-23b2b480-4b81-11ea-9f97-fba448063204.jpg)

**Comment by benleb** [comment]
Did you maybe mix up something or configured a wrong sensor for illumination?
```
if float(self.get_state(sensor)) >= self.illuminance_threshold
ValueError: could not convert string to float: 'on'
```
This says the state of the sensor was `on` but it seems that does not match to your screenshot, which shows a sensor giving numbers and not "on/off" (binary sensor?)?! I have no experience with deconz, but it should work in general :)

**Comment by benleb** [comment]
you can also test this change (vi hacs master or simply change the lines in the automoli.py) which gives a more detailed error message... https://github.com/benleb/ad-automoli/commit/8bb32d542418b99029de45b48675456699893179

**Comment by chbndrhnns** [comment]
I will check this next week. I am currently not at home for testing.

**Comment by chbndrhnns** [comment]
It was my fault. I used the same sensor entity for both motion and illumination. Instead, I should not have used the binary sensor for illumination.
