### ISSUE TITLE
Log 

### ISSUE THREAD

**Issue by gogui63** [benleb/ad-automoli#21]
Hello,

I'm starting with HA and AppDeamon, nothing seems to work on my installation :) 

To undertsand why, how/where can I check log for this app ? 

My config : 
auto_lights_hall:
  module: automoli
  class: AutoMoLi
  room: hall
  delay: 180
  daytimes:
    - { starttime: "00:01", name: night, light: 10 }
    - { starttime: "05:30", name: morning, light: 45 }
    - { starttime: "07:30", name: day, light: 30 }
    - { starttime: "22:30", name: evening, light: 150 }
    - { starttime: "23:30", name: night, light: 80 }
  lights:
    - light.hall
  motion:
    - binary_sensor.motion_sensor_hall_entree
    - binary_sensor.motion_sensor_hall

In /config/appdaemon/logs/appdaemon.log I ve only log for appdeamon not apps.

I'm sorry for my neewbie question :)

**Comment by benleb** [comment]
First, no problem :)

About Logs, you can configure where the logs go in AppDaemon configuration, see https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#log-configuration for more details.
Do you see any errors that AutoMoLi could not be loaded in the `appdaemon.log`? Or did you config log related stuff in AppDaemon? If not, any logs should be written to stdout (shown where you start AppDaemon) afaik.

Or are you using something like Hass.io or anything? In this case I would expect all logs to go at least to `config/appdaemon/logs/`, but i do not know anything about. Maybe there are other files in this folder?

You can tell me a little more details about your setup and I should be able to help you at least by pointing you to the correct contect fpr this issue :)

**Comment by gogui63** [comment]
Thanks for your help ! 

I well configured logs like this : 
`
logs:
  main_log:
    filename: /config/appdaemon/logs/appdaemon.log
  access_log:
    filename: /config/appdaemon/logs/access.log
  error_log:
    filename: /config/appdaemon/logs/error.log
  diag_log:
    filename: /config/appdaemon/logs/diag.log
    log_generations: 5
    log_size: 1024
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"
  automoli_log:
    name: AutoMoLi
    filename: /config/appdaemon/logs/automoli.log`

I've not error concerning Automoli in AppDaemons logs but my lights doesn't on when a motion sensor is trigger.
I'm ussing Hassio 0.105.2 (last stable version) on Intel NUC (debian 9). 
My lights are Philips Hue Lights and motion sensors are Xiaomi sensors

**Comment by benleb** [comment]
Ah okay, but afaik that configuration will not do what you expect (logging all logs from AutoMoLi to a separate file). Remove the automoli stuff from the log section completely, then you should get the logs to `appdaemon.log`

The Log snippet means AppDaemon could not find the configuration for AutoMoli?! Maybe you put it in a wrong file? The configuration for apps are (by default) in a file called `apps.yaml`. I do not know where it is on Hass.io, but I guess it could be `/config/appdaemon/apps/apps.yaml`

**Comment by gogui63** [comment]
OOh yeah ! I've put everything in appdaemon.yaml, now "works fine" in apps.yaml inside config/appdaemon/apps/

Now I've in logs : 

> 2020-02-09 16:50:13.723285 WARNING Error: ------------------------------------------------------------
2020-02-09 16:50:13.724146 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/automoli/automoli.py:
2020-02-09 16:50:13.725022 WARNING Error: ------------------------------------------------------------
2020-02-09 16:50:13.730458 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 788, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 580, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/automoli/automoli.py", line 32, in <module>
    from adutils import ADutils, hl
ModuleNotFoundError: No module named 'adutils'

2020-02-09 16:50:13.731370 WARNING Error: ------------------------------------------------------------

**Comment by benleb** [comment]
Okay, thats a duplicate - lets talk in the other issue #15 about. Closing this here :)
