### ISSUE TITLE
App not loading

### ISSUE THREAD

**Issue by samnewman86** [benleb/ad-automoli#26]
The app isn't loading properly. Can't find module adutils. See appdaemon log below.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.1.2
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.105.3
 Supervisor version: 200
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:35:39] INFO: Starting AppDaemon...
2020-02-14 11:35:39.729553 INFO AppDaemon: AppDaemon Version 4.0.1 starting
2020-02-14 11:35:39.729724 INFO AppDaemon: Python version is 3.8.1
2020-02-14 11:35:39.729847 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-02-14 11:35:39.729958 INFO AppDaemon: Added log: AppDaemon
2020-02-14 11:35:39.730076 INFO AppDaemon: Added log: Error
2020-02-14 11:35:39.730186 INFO AppDaemon: Added log: Access
2020-02-14 11:35:39.730294 INFO AppDaemon: Added log: Diag
2020-02-14 11:35:39.740978 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-02-14 11:35:39.758290 INFO HASS: HASS Plugin Initializing
2020-02-14 11:35:39.758473 INFO HASS: HASS Plugin initialization complete
2020-02-14 11:35:39.758783 INFO AppDaemon: Initializing HTTP
2020-02-14 11:35:39.759032 INFO AppDaemon: Using 'ws' for event stream
2020-02-14 11:35:39.766941 INFO AppDaemon: Starting API
2020-02-14 11:35:39.769862 INFO AppDaemon: Starting Admin Interface
2020-02-14 11:35:39.770135 INFO AppDaemon: Starting Dashboards
2020-02-14 11:35:39.779156 INFO HASS: Connected to Home Assistant 0.105.3
2020-02-14 11:35:39.816273 INFO AppDaemon: App 'bathroom_lights' added
2020-02-14 11:35:39.816999 INFO AppDaemon: Found 1 total apps
2020-02-14 11:35:39.817390 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2020-02-14 11:35:39.818118 INFO AppDaemon: Running on port 5050
2020-02-14 11:35:39.841651 INFO HASS: Evaluating startup conditions
2020-02-14 11:35:39.862972 INFO AppDaemon: Got initial state from namespace default
2020-02-14 11:35:40.658732 INFO AppDaemon: New client Admin Browser connected
2020-02-14 11:35:41.821969 INFO AppDaemon: Scheduler running in realtime
2020-02-14 11:35:41.827014 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-02-14 11:35:41.827565 INFO AppDaemon: Adding /config/appdaemon/apps/automoli to module import path
2020-02-14 11:35:41.831721 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/automoli/__init__.py - ignoring
2020-02-14 11:35:41.832929 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/automoli/pkg_helper.py - ignoring
2020-02-14 11:35:41.834360 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/automoli/automoli.py
installing required packages: {'adutils~=0.4.9'}
{'adutils~=0.4.9'} successfully installed!
2020-02-14 11:35:42.814745 WARNING Error: ------------------------------------------------------------
2020-02-14 11:35:42.815546 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/automoli/automoli.py:
2020-02-14 11:35:42.815755 WARNING Error: ------------------------------------------------------------
2020-02-14 11:35:42.817342 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 788, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 580, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/automoli/automoli.py", line 69, in <module>
    from adutils import ADutils, hl
ModuleNotFoundError: No module named 'adutils'

2020-02-14 11:35:42.817594 WARNING Error: ------------------------------------------------------------
2020-02-14 11:35:42.817796 WARNING AppDaemon: Removing associated apps:
2020-02-14 11:35:42.817995 WARNING AppDaemon: bathroom_lights
2020-02-14 11:35:42.818665 INFO AppDaemon: App initialization complete`

**Comment by benleb** [comment]
Try restarting appdaemon :) It’s fixed in master already but I would not recommend installing it unless you can fix some problems yourself.
I am on the way to release a fixed version in a few hours :)

**Comment by samnewman86** [comment]
Wow, that was quick, thanks.
What was causing the issue?

**Comment by samnewman86** [comment]
Just to follow up, I installed master and it's working :-) nice one :+1:

**Comment by benleb** [comment]
should be fixed (without needing a restart) in [v0.6.0](https://github.com/benleb/ad-automoli/releases/tag/v0.6.0). can you confirm this?

**Comment by samnewman86** [comment]
I had an error, restarted appdaemon and all good, thanks 👍
