### ISSUE TITLE
event_listener not working for NON-Xiaomi Motion Sensors

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-automoli#3]
HI! Thanks again for this woonderfull App but I think there's an issue with the motion event listener. it only listens to xiaomi events if i read the code well. I have z-wave fibaro sensors which won't trigger

This might be the part of the xiaomi motion event listener but no other motion event listeners are in the code :

```

EVENT_MOTION = "xiaomi_aqara.motion"

```

**Comment by thundergreen** [comment]
I changed the EVENT_MOTION = "xiaomi_aquara.motion" to EVENT_MOTION = "state_changed" 

It works so far but this is the error trace in logs:


```2019-10-15 11:21:30.054182 WARNING stairs_night: ------------------------------------------------------------


2019-10-15 11:21:30.054638 WARNING stairs_night: Unexpected error in worker for App stairs_night:


2019-10-15 11:21:30.054992 WARNING stairs_night: Worker Ags: {'id': 'e60ed18bf69843a087e15fc687af8d55', 'name': 'stairs_night', 'objectid': '2de4289faef54a74bf83765589fef2ec', 'type': 'event', 'event': 'state_changed', 'function': <bound method AutoMoLi.motion_event of <automoli.AutoMoLi object at 0x7fd254f1e6d0>>, 'data': {'entity_id': 'binary_sensor.motion_downstairs', 'old_state': {'entity_id': 'binary_sensor.motion_downstairs', 'state': 'off', 'attributes': {'node_id': 17, 'value_index': 0, 'value_instance': 1, 'value_id': '72057594328121344', 'friendly_name': 'Multisensor Downstairs', 'device_class': 'motion'}, 'last_changed': '2019-10-15T09:20:23.405255+00:00', 'last_updated': '2019-10-15T09:20:23.405255+00:00', 'context': {'id': '620eaac1539243158c822a139db9e69f', 'parent_id': None, 'user_id': None}}, 'new_state': {'entity_id': 'binary_sensor.motion_downstairs', 'state': 'on', 'attributes': {'node_id': 17, 'value_index': 0, 'value_instance': 1, 'value_id': '72057594328121344', 'friendly_name': 'Multisensor Downstairs', 'device_class': 'motion'}, 'last_changed': '2019-10-15T09:21:30.023130+00:00', 'last_updated': '2019-10-15T09:21:30.023130+00:00', 'context': {'id': 'f9c280903da04e62bfa056447acc80d5', 'parent_id': None, 'user_id': None}}}, 'pin_app': True, 'pin_thread': 4, 'kwargs': {'entity_id': 'binary_sensor.motion_downstairs', '__thread_id': 'thread-4'}}


2019-10-15 11:21:30.055323 WARNING stairs_night: ------------------------------------------------------------


2019-10-15 11:21:30.055762 WARNING stairs_night: Traceback (most recent call last):


  File "/usr/local/lib/python3.7/site-packages/appdaemon/threading.py", line 776, in worker


    funcref(args["event"], data, args["kwargs"])


  File "/conf/apps/automoli.py", line 224, in motion_event


    self.lights_on()


  File "/conf/apps/automoli.py", line 249, in lights_on


    if isinstance(self.active["light_setting"], str):


KeyError: 'light_setting'




2019-10-15 11:21:30.056052 WARNING stairs_night: ------------------------------------------------------------


2019-10-15 11:21:30.089047 INFO stairs_day: 💡 Stairs turned on → brightness: 100%
```

**Comment by thundergreen** [comment]
this is stairs night settings:

```
stairs_night:
  module: automoli
  class: AutoMoLi
  room: stairs
  disable_switch_entity: input_boolean.automoli_stairs
  delay: 60
  daytimes:
    - { starttime: "22:30", name: night, light: 100 }
  illuminance_threshold: 80
  lights:
    - light.xiaomi_gateway
  motion:
    - binary_sensor.motion_downstairs
    - binary_sensor.motion_upstairs
  illuminance:
    - sensor.average_luminance_stairs
```

**Comment by thundergreen** [comment]
and this is stairs_day:
```
stairs_day:
  module: automoli
  class: AutoMoLi
  room: stairs
  disable_switch_entity: input_boolean.automoli_stairs
  delay: 60
  daytimes:
    - { starttime: "07:30", name: morning, light: 1 }
    - { starttime: "08:00", name: day, light: 100  }
    - { starttime: "20:00", name: evening, light: 1 }
  illuminance_threshold: 80
  lights:
    - light.spots_stairs
  motion:
    - binary_sensor.motion_downstairs
    - binary_sensor.motion_upstairs
  illuminance:
    - sensor.average_luminance_stairs
```

I don't see se error or difference between those two configs :/

**Comment by thundergreen** [comment]
Now the fibaro motion_sensors work well but my xiaomi motion sensor in the bathroom stopped. It seems that your app listens either to xiaomi event or state chaned events.. is it possible to add both?

**Comment by thundergreen** [comment]
Any news here @benleb ?

**Comment by benleb** [comment]
Hey, sorry. Good catch, thats because all people I knew of used xiaomi sensors - until now ;)
But... I am currently in the last weeks of my masters thesis so probably I wont have time to fix this until the weekend of 9./10. of november :/ sorry!

Thanks for your contributions @thundergreen and sorry for my temporary absence!

**Comment by thundergreen** [comment]
That's ok .I recently had to setup hassio froma scratch and I'm patient as
I wanna rewrite my config a bit later and I'm also in training till 11
November..take your time mate

Ben Lebherz <notifications@github.com> schrieb am Sa., 26. Okt. 2019, 06:55:

**Comment by benleb** [comment]
hey, should work in https://github.com/benleb/ad-automoli/releases/tag/v0.4.7 :)
set the new config option `motion_event` to "state_changed" and it listens also for your fibaro events :)

if this does not work as expected, please reopen this issue. thanks!

**Comment by thundergreen** [comment]
@benleb works! please update doc.. or wait i will make a pull request :) Thanks a lot!!!!

**Comment by bluehallu** [comment]
@benleb this option is now deprecated so not sure how to use it with my Ikea motion sensor, the readme also doesn't mention anything about it only working with Xiaomi by default

**Comment by benleb** [comment]
@bluehallu create a new issue please :)
