### ISSUE TITLE
Unable to find module - Example configuration

### ISSUE THREAD

**Issue by ollioddi** [benleb/ad-automoli#36]
First of all this is out of my usual experience level and im new to home assistant. I do though have a generel understanding of this.

I am experiencing an error with the example configuration.

This is my apps.yaml config:

> Livingroom:
  module: automoli
  class: AutoMoLi
  room: Livingroom
  delay: 600
  daytimes:
    - { starttime: "05:30", name: morning, light: "Morning" }
    - { starttime: "07:30", name: day, light: "Working" }
    - { starttime: "20:30", name: evening, light: 90 }
    - { starttime: "22:30", name: night, light: 20 }
    - { starttime: "23:30", name: more_night, light: 0 }
  lights:
    - light.loft_2
    - light.loft_1
  motion:
    - binary_sensor.pir_1
  humidity:
    - sensor.aeon_labs_zw100_multisensor_6_relative_humidity
>

I am getting the following error:

> 2020-03-18 22:08:26.210700 INFO AppDaemon: Initializing app Livingroom using class AutoMoLi from module automoli
2020-03-18 22:08:26.211242 WARNING Livingroom: ------------------------------------------------------------
2020-03-18 22:08:26.211473 WARNING Livingroom: Unexpected error initializing app: Livingroom:
2020-03-18 22:08:26.211671 WARNING Livingroom: ------------------------------------------------------------
2020-03-18 22:08:26.212437 WARNING Livingroom: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
2020-03-18 22:08:26.212830 WARNING Livingroom: ------------------------------------------------------------
2020-03-18 22:08:26.213128 WARNING AppDaemon: Unable to find module Livingroom - initialize() skipped
2020-03-18 22:08:26.213512 INFO AppDaemon: App initialization complete
> 

Can someone tell me if its a Automoli issue or if i have configured AppDaemon incorrect?

Thanks in advance, i would really appreciate some help.

**Comment by benleb** [comment]
Looks like an [AppDaemon](http://appdaemon.readthedocs.io/en/stable/) problem, close for now :)

**Comment by SergioRius** [comment]
Having the same exact problem. Logs show:
```
2022-09-06 21:06:06.287511 WARNING AppDaemon: Unable to find module hallway_back - initialize() skipped
2022-09-06 21:06:06.286314 WARNING AppDaemon: Logged an error to /home/appdaemon/.appdaemon/log/error.log
2022-09-06 21:06:05.236410 INFO AppDaemon: Initializing app hallway_back using class AutoMoLi from module automoli
```
Error log shows that is trying to load an inexistent module 'adutils':
```
2022-09-06 21:06:06.286088 WARNING hallway_back: -----------------------
2022-09-06  21:06:06.285866 WARNING hallway_back: Traceback (most recent call  last):   File "/home/appdaemon/.appdaemon/conf/apps/automoli/automoli.py", line  92, in install_pip_package     importlib.import_module(pkg)   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in  import_module     return _bootstrap._gcd_import(name[level:], package, level)   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import   File "<frozen importlib._bootstrap>", line 1007, in  _find_and_load   File "<frozen importlib._bootstrap>", line 984, in  _find_and_load_unlocked ModuleNotFoundError: No module named 'adutils'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/home/appdaemon/.appdaemon/conf/apps/automoli/automoli.py", line  108, in install_pip_package     check_call(   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call     raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m',  'pip', 'install', '--upgrade', 'adutils>=0.6.2']' returned non-zero  exit status 2.  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File  "/home/appdaemon/.local/lib/python3.9/site-packages/appdaemon/app_management.py",  line 1026, in check_app_updates     await self.init_object(app)   File  "/home/appdaemon/.local/lib/python3.9/site-packages/appdaemon/app_management.py",  line 321, in init_object     modname = await utils.run_in_executor(self, __import__,  app_args["module"])   File  "/home/appdaemon/.local/lib/python3.9/site-packages/appdaemon/utils.py",  line 337, in run_in_executor     response = future.result()   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in  run     result = self.fn(*self.args, **self.kwargs)   File "/home/appdaemon/.appdaemon/conf/apps/automoli/automoli.py", line  124, in <module>     install_pip_package("adutils", version=">=0.6.2")   File "/home/appdaemon/.appdaemon/conf/apps/automoli/automoli.py", line  120, in install_pip_package     importlib.import_module(pkg)   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in  import_module     return _bootstrap._gcd_import(name[level:], package, level) ModuleNotFoundError: No module named 'adutils'
2022-09-06 21:06:06.285189 WARNING hallway_back: -------------------------
2022-09-06 21:06:06.285014 WARNING hallway_back: Unexpected error initializing app: hallway_back:
```
Been using appdaemon with controllerx without a problem.
Running v4.2.2
