### ISSUE TITLE
ValueError: could not convert string to float: 'unavailable'

### ISSUE THREAD

**Issue by chbndrhnns** [benleb/ad-automoli#44]
I noticed this error today in my logs:

```
2020-07-15 07:20:51.007807 WARNING bathroom_automoli: Unexpected error in worker for App bathroom_automoli:
2020-07-15 07:20:51.008158 WARNING bathroom_automoli: Worker Ags: {'id': '1b2479fe6dfa42e28635d165700c95b5', 'name': 'bathroom_automoli', 'objectid': 'bd68eb2316b6415983f3abca2f090419', 'type': 'scheduler', 'function': <bound method AutoMoLi.lights_off of <automoli.AutoMoLi object at 0x7f4463612bb0>>, 'pin_app': True, 'pin_thread': 4, 'kwargs': {'__thread_id': 'thread-4'}}
2020-07-15 07:20:51.008458 WARNING bathroom_automoli: ------------------------------------------------------------
2020-07-15 07:20:51.009063 WARNING bathroom_automoli: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 766, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 330, in lights_off
    blocker = [
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 333, in <listcomp>
    if float(self.get_state(sensor)) >= self.thresholds["humidity"]
ValueError: could not convert string to float: 'unavailable'
```

It seems to be related to some unavailable sensor. Could we maybe ignore the configured sensor threshold and switch off the light instead?

**Comment by benleb** [comment]
should be fixed :) to get it, please use the master or give me 1-2 more days ;)
