### ISSUE TITLE
illuminance_threshold cause error

### ISSUE THREAD

**Issue by sivastola** [benleb/ad-automoli#45]
Hi, I'm having a problem with the illluminance value. 
Here is my configuration:
---- the script for appdaemon----BEGIN
flurstern:
  module: automoli
  class: AutoMoLi
  room: Flurstern
  delay: 60
  daytimes:
    - { starttime: "05:30", name: morning, light: "light.flurstern" }
    - { starttime: "07:30", name: day, light: "light.flurstern" }
  illuminance: sensor.000d5a49919777_average_illumination
  illuminance_threshold: 40
  lights:
    - light.flurstern
  motion:
    - binary_sensor.aqara_motion2
    - binary_sensor.presence_15
  motion_state_on: "on"
  motion_state_off: "off"
---- the script for appdaemon----END

the sensor is from Homematic
![image](https://user-images.githubusercontent.com/58854464/89057982-ca248900-d35e-11ea-93f3-62ecb4a6ce7b.png)

If I delete the line "illuminance_threshold: 40" the script works as expected, and the light goes on and off if the motion sensor detects something.

If the threshold value is active I get this error as soon as motion is detected:
2020-07-31 18:27:32.180735 WARNING Flurstern: ------------------------------------------------------------
2020-07-31 18:27:32.182503 WARNING Flurstern: Unexpected error in worker for App Flurstern:
2020-07-31 18:27:32.182983 WARNING Flurstern: Worker Ags: {'id': 'c49e967de284412491621db173477f56', 'name': 'Flurstern', 'objectid': 'f5516d89776f4f9592711ae121561347', 'type': 'state', 'function': <bound method AutoMoLi.motion_detected of <automoli.AutoMoLi object at 0x7f10ef18a100>>, 'attribute': 'state', 'entity': 'binary_sensor.aqara_motion2', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'new': 'on', '__thread_id': 'thread-0'}}
2020-07-31 18:27:32.183497 WARNING Flurstern: ------------------------------------------------------------
2020-07-31 18:27:32.183993 WARNING Flurstern: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 210, in motion_detected
    self.motion_event("state_changed_detection", data, kwargs)
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 227, in motion_event
    self.lights_on()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 257, in lights_on
    if float(self.get_state(sensor)) >= self.thresholds["illuminance"]:
TypeError: float() argument must be a string or a number, not 'dict'
2020-07-31 18:27:32.185391 WARNING Flurstern: ------------------------------------------------------------

Did I miss something?
regards

**Comment by benleb** [comment]
hmm... I will have a look at this on the weekend, sorry!

**Comment by sivastola** [comment]
take your time. Thanks for watching, and providing this nice peace of software

**Comment by benleb** [comment]
fixed in master, release follows in the next days

**Comment by sivastola** [comment]
works now. thanks
