### ISSUE TITLE
Unavailable entity throws error

### ISSUE THREAD

**Issue by chbndrhnns** [benleb/ad-automoli#52]
I get this error when a deconz entity is not available:

```
2020-10-11 18:56:16.015232 WARNING bathroom_automoli: Unexpected error in worker for App bathroom_automoli:
2020-10-11 18:56:16.015795 WARNING bathroom_automoli: Worker Ags: {'id': '6551b500931b4fc880e303b095baa2ff', 'name': 'bathroom_automoli', 'objectid': '5d1fdd11ed98484083239056d93e2200', 'type': 'scheduler', 'function': <bound method AutoMoLi.lights_off of <automoli.AutoMoLi object at 0x7f870f37f340>>, 'pin_app': True, 'pin_thread': 3, 'kwargs': {'__thread_id': 'thread-3'}}
2020-10-11 18:56:16.016717 WARNING bathroom_automoli: ------------------------------------------------------------
2020-10-11 18:56:16.017463 WARNING bathroom_automoli: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 887, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 330, in lights_off
    blocker = [
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 333, in <listcomp>
    if float(self.get_state(sensor)) >= self.thresholds["humidity"]
ValueError: could not convert string to float: 'unavailable'
```

**Comment by benleb** [comment]
seems you are running an old version?!

**Comment by chbndrhnns** [comment]
you are right. I was troubleshooting a connectivity issue and assumed automoli to be the faulty part. The error disappeared with the latest version. Thanks!
