### ISSUE TITLE
Error: cannot import name 'Room' from 'adutils'

### ISSUE THREAD

**Issue by paviro** [benleb/ad-automoli#71]
Just came back home, will test night mode soon!

BUUUT I got another new bug after the last update 😄 

```
2021-04-05 14:30:11.865143 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 963, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 741, in read_app
    importlib.reload(self.modules[module_name])
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 114, in <module>
    from adutils import (  # noqa
ImportError: cannot import name 'Room' from 'adutils' (/usr/lib/python3.8/site-packages/adutils/__init__.py)
2021-04-05 14:30:11.866790 WARNING Error: ------------------------------------------------------------
2021-04-05 14:30:11.868138 WARNING AppDaemon: Removing associated apps:
2021-04-05 14:30:11.869494 WARNING AppDaemon: badezimmer_bewegungsmelder
```

**Comment by gardar** [comment]
I'm getting the same error after updating, so unfortunately I can't resolve it by updating homeassistant like @paviro did.

I'm on versions:
Homeassistant: 021.4.6
Appdaemon: 4.0.8
ad-automoli: v0.11.0

```
Apr 28 02:10:07 ha01 appdaemon[1864]: 2021-04-28 02:10:07.983241 WARNING Error: Unexpected error loading module: /home/g/.homeassistant/appdaemon/apps/ad-autom│
oli/automoli.py:                                                                                                                                               │
Apr 28 02:10:07 ha01 appdaemon[1864]: 2021-04-28 02:10:07.983373 WARNING Error: ------------------------------------------------------------                   │
Apr 28 02:10:07 ha01 appdaemon[1864]: 2021-04-28 02:10:07.984585 WARNING Error: Traceback (most recent call last):                                             │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "/opt/appdaemon/lib/python3.8/site-packages/appdaemon/app_management.py", line 963, in check_app_updates          │
Apr 28 02:10:07 ha01 appdaemon[1864]:     await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])                                         │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "/opt/appdaemon/lib/python3.8/site-packages/appdaemon/utils.py", line 299, in run_in_executor                     │
Apr 28 02:10:07 ha01 appdaemon[1864]:     response = future.result()                                                                                           │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run                                                │
Apr 28 02:10:07 ha01 appdaemon[1864]:     result = self.fn(*self.args, **self.kwargs)                                                                          │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "/opt/appdaemon/lib/python3.8/site-packages/appdaemon/app_management.py", line 755, in read_app                   │
Apr 28 02:10:07 ha01 appdaemon[1864]:     self.modules[module_name] = importlib.import_module(module_name)                                                     │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module                                            │
Apr 28 02:10:07 ha01 appdaemon[1864]:     return _bootstrap._gcd_import(name[level:], package, level)                                                          │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                        │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                      │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                             │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                      ├
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                           │
Apr 28 02:10:07 ha01 appdaemon[1864]:   File "/home/g/.homeassistant/appdaemon/apps/ad-automoli/automoli.py", line 114, in <module>                            │
Apr 28 02:10:07 ha01 appdaemon[1864]:     from adutils import (  # noqa                                                                                        │
Apr 28 02:10:07 ha01 appdaemon[1864]: ImportError: cannot import name 'Room' from 'adutils' (/opt/appdaemon/lib/python3.8/site-packages/adutils/__init__.py)   │
Apr 28 02:10:07 ha01 appdaemon[1864]: 2021-04-28 02:10:07.984797 WARNING Error: ------------------------------------------------------------                   │
Apr 28 02:10:07 ha01 appdaemon[1864]: 2021-04-28 02:10:07.984933 WARNING AppDaemon: Removing associated apps:                                                  │

```

Any thoughts @benleb?

**Comment by benleb** [comment]
hmm did you restart appdaemon after upgrading?

**Comment by gardar** [comment]
@benleb, sorry I missed your reply.
I was updating homeassistant today and I tried to update to ad-automoli v0.11 again and I still get this error... I find it kind of strange that there aren't more users reporting the same.
To reply to your question, yes I did restart appdaemon and I even restarted the whole server several times.
