### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mon3y78** [benleb/ad-automoli#81]
i have this error

AttributeError: 'AutoMoLi' object has no attribute 'room'
2021-07-25 10:40:32.635202 WARNING camera_weekend: ------------------------------------------------------------
2021-07-25 10:40:32.642195 INFO cucina:  
2021-07-25 10:40:32.643475 WARNING cucina: ------------------------------------------------------------
2021-07-25 10:40:32.644476 WARNING cucina: Unexpected error running initialize() for cucina
2021-07-25 10:40:32.645597 WARNING cucina: ------------------------------------------------------------
2021-07-25 10:40:32.646922 WARNING cucina: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 215, in initialize
    self.lg("")
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 163, in lg
    name=self.room.name.capitalize(),  # type:ignore

😩 **Describe the issue/bug**

😒 **Expected behavior**

🎛️ **Configuration**
```yaml
[relevant configuration from your apps.yml file]
```

🧠 **System**
 - AppDaemon: **[e.g. 4.0.5]**
   -  running mode: **[e.g. virtualenv, hassio-plugin, docker]**
 - Home-Assistant: **[e.g. 0.118.3, 0.119.0b0]**
   -  running mode: **[e.g. virtualenv, hassio, docker]**
 - Python: **[e.g. 3.8.6, 3.9]**

🗒️ **Logs** 

```log
log log log...
```

🧁 **Additional context**

**Comment by benleb** [comment]
Thanks, my fault 🙄 Fixed in the master now :) release follows soon...

**Comment by mon3y78** [comment]
thanks, now work!
